# Generated by Django 6.0.5 on 2026-07-15 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0002_historicalmedicalrecord"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medicalrecord",
            options={"ordering": ["-created_at"]},
        ),
    ]
