# Generated by Django 6.0.5 on 2026-06-21 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="clinics.clinicgroup",
            ),
        ),
    ]
