# Generated by Django 6.0.5 on 2026-06-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_clinic"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="invitation",
            unique_together=set(),
        ),
    ]
