# Generated by Django 6.0.5 on 2026-07-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_invitation_unique_together"),
        ("clinics", "0002_delete_workinghours"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "sent")),
                fields=("email", "clinic"),
                name="unique_pending_invitation_per_email_per_clinic",
            ),
        ),
    ]
