# Generated by Django 6.0.5 on 2026-07-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0003_alter_medicalrecord_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmedicalrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalmedicalrecord',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
