# Generated by Django 6.0.5 on 2026-07-15 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0005_alter_clinic_options_alter_clinicgroup_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clinic",
            options={"ordering": ["id"]},
        ),
    ]
