# Generated by Django 6.0.5 on 2026-06-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkingHours",
        ),
    ]
