# Generated by Django 6.0.5 on 2026-07-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0003_clinic_created_at_clinic_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clinic",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="clinicgroup",
            options={"ordering": ["id"]},
        ),
    ]
