# Generated by Django 6.0.5 on 2026-06-28 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0001_initial"),
        ("owners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owners",
                to="clinics.clinicgroup",
            ),
        ),
    ]
