# Generated by Django 6.0.5 on 2026-07-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0002_delete_workinghours"),
        ("owners", "0002_owner_clinic"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="owner",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email", ""), _negated=True),
                fields=("email", "clinic"),
                name="unique_email_per_clinic",
            ),
        ),
    ]
