# Generated by Django 6.0.5 on 2026-07-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("owners", "0004_owner_created_at_owner_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="owner",
            options={"ordering": ["id"]},
        ),
    ]
