# Generated by Django 6.0.5 on 2026-07-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0006_alter_clinic_options"),
        ("owners", "0007_alter_owner_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="owner",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email", ""), _negated=True),
                fields=("email", "clinic"),
                name="unique_email_per_clinic",
            ),
        ),
    ]
