# Generated by Django 6.0.5 on 2026-07-15 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_created_at_user_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invitation",
            options={"ordering": ["id"]},
        ),
    ]
