"""
Shared helpers for exposing django-simple-history audit trails over the API.

Pet, Vaccination and MedicalRecord all carry `HistoricalRecords()`, but until
now nothing surfaced those versions to clients, so the audit trail existed in
the database and nowhere else. These helpers build a read-only serializer and
list view per model, so every history endpoint has the same shape:

    {
      "history_id": 12,
      "history_date": "2026-07-21T09:15:00Z",
      "history_type": "~",
      "history_type_label": "updated",
      "history_user": "vet@clinic.com",
      ... a snapshot of the tracked fields at that point in time ...
    }

There is no `common` models module, so this package deliberately has no
AppConfig and does not belong in INSTALLED_APPS.
"""

from rest_framework import generics, permissions, serializers

HISTORY_TYPE_LABELS = {
    "+": "created",
    "~": "updated",
    "-": "deleted",
}

# Present on every historical model generated by django-simple-history.
HISTORY_META_FIELDS = [
    "history_id",
    "history_date",
    "history_type",
    "history_type_label",
    "history_user",
]


def build_history_serializer(model, fields):
    """
    Returns a read-only serializer for `model`'s historical table.

    `fields` lists the tracked model fields to include in each snapshot; the
    history metadata columns are prepended automatically.
    """
    historical_model = model.history.model
    tracked_fields = list(fields)

    class _HistorySerializer(serializers.ModelSerializer):
        # The FK points at a user row that may since have been deactivated, so
        # read the email defensively rather than nesting a full serializer.
        history_user = serializers.SerializerMethodField()
        history_type_label = serializers.SerializerMethodField()

        class Meta:
            model = historical_model
            fields = HISTORY_META_FIELDS + tracked_fields
            read_only_fields = fields

        def get_history_user(self, obj) -> str | None:
            return getattr(obj.history_user, "email", None)

        def get_history_type_label(self, obj) -> str:
            return HISTORY_TYPE_LABELS.get(obj.history_type, obj.history_type)

    _HistorySerializer.__name__ = f"Historical{model.__name__}Serializer"
    return _HistorySerializer


class BaseHistoryView(generics.ListAPIView):
    """
    Lists every revision of one record, newest first.

    Subclasses provide `get_scoped_queryset()` returning the *live* objects the
    caller is allowed to see. Resolving the parent through that queryset is what
    enforces multi-tenancy: a record belonging to another ClinicGroup 404s here
    exactly as it does on the detail endpoint, so history can't be used as a
    side channel to confirm that some other clinic's record exists.
    """

    permission_classes = [permissions.IsAuthenticated]

    def get_scoped_queryset(self):
        raise NotImplementedError

    def get_queryset(self):
        if getattr(self, "swagger_fake_view", False):
            return self.serializer_class.Meta.model.objects.none()

        parent = generics.get_object_or_404(
            self.get_scoped_queryset(), pk=self.kwargs["pk"]
        )
        return parent.history.all()
