# Generated by Django 6.0.5 on 2026-07-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owners", "0003_owner_unique_email_per_clinic"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="owner",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
