# Generated by Django 6.0.5 on 2026-07-15 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("owners", "0005_alter_owner_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="owner",
            options={},
        ),
    ]
