# Generated by Django 6.0.5 on 2026-07-15 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("owners", "0006_alter_owner_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="owner",
            options={"ordering": ["id"]},
        ),
        migrations.RemoveConstraint(
            model_name="owner",
            name="unique_email_per_clinic",
        ),
    ]
