# Generated by Django 6.0.5 on 2026-07-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0008_owner_unique_email_per_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
