# Generated by Django 6.0.5 on 2026-06-20 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("owners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("dog", "Dog"),
                            ("cat", "Cat"),
                            ("rabbit", "Rabbit"),
                            ("bird", "Bird"),
                            ("hamster", "Hamster"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("female", "Female"), ("male", "Male")], max_length=6
                    ),
                ),
                ("breed", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("birth_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="pets/"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="owners.owner"
                    ),
                ),
            ],
        ),
    ]
