# Generated by Django 6.0.5 on 2026-06-28 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owners", "0002_owner_clinic"),
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="allergies",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="diet",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="pet",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to="owners.owner",
            ),
        ),
        migrations.CreateModel(
            name="Vaccination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vaccine_name", models.CharField(max_length=100)),
                ("date_given", models.DateField()),
                ("next_due", models.DateField()),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vaccinations",
                        to="pets.pet",
                    ),
                ),
            ],
        ),
    ]
