# Generated by Django 6.0.5 on 2026-06-29 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owners", "0002_owner_clinic"),
        ("pets", "0002_pet_allergies_pet_diet_alter_pet_owner_vaccination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to="owners.owner",
            ),
        ),
    ]
