# Generated by Django 6.0.5 on 2026-07-08 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0003_alter_pet_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="image",
        ),
    ]
