# Generated by Django 6.0.5 on 2026-07-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0004_remove_pet_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
