# Generated by Django 6.0.5 on 2026-07-15 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0006_historicalpet_historicalvaccination"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pet",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="vaccination",
            options={"ordering": ["pet", "date_given"]},
        ),
    ]
